server:
  port: 8002

#aliyun
spring:
  cloud:
    alicloud:
      access-key: LTAI4GDR68tGrgGWiuzKgF8L
      secret-key: a4ILbgMnH6LvQHKpCUQkmBcn4SaNRo
#      access-key: xxxx
#      secret-key: xxxx
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: mooc-edu-xxliuxx
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#MyBatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#nacos
spring.cloud.nacos.discovery.server-addr: 127.0.0.1:8848
